#!/bin/sh

ROOM=0
if [ -f /tmp/current-temp ] ; then
    ROOM=1
fi
OMNIA=0
if [ -x /usr/bin/thermometer ] ; then
    OMNIA=1
fi
SDA=0
SDB=0
if [ -x /usr/sbin/smartctl ] ; then
    if [ -b /dev/sda ] ; then
        SDA=1
    fi
    if [ -b /dev/sdb ] ; then
        SDB=1
    fi
fi

if [ "$1" = "config" ] ; then
    echo "graph_title Temperature"
    echo "graph_args --base 1000 -l 0 -u 40"
    echo "graph_vlabel room temperature"
    echo "graph_category other"
    echo "graph_info This graph shows the room temperature."
    if [ $ROOM -eq 1 ] ; then
        echo "temp.label temperature"
        echo "temp.draw LINE2"
        echo "temp.info The current room temperature."
    fi
    if [ $OMNIA -eq 1 ] ; then
        echo "cputemp.label CPU"
        echo "cputemp.draw LINE2"
        echo "cputemp.info The current CPU temperature."
    fi
    if [ $SDA -eq 1 ] ; then
        echo "sdatemp.label sda"
        echo "sdatemp.draw LINE2"
        echo "sdatemp.info The current sda disk temperature."
    fi
    if [ $SDB -eq 1 ] ; then
        echo "sdbtemp.label sdb"
        echo "sdbtemp.draw LINE2"
        echo "sdbtemp.info The current sdb disk temperature."
    fi
    exit 0
fi

if [ $ROOM -eq 1 ] ; then
    echo "temp.value" $(cat /tmp/current-temp)
fi
if [ $OMNIA -eq 1 ] ; then
    echo "cputemp.value" $(thermometer | sed -rn 's/CPU.*[[:space:]]([0-9]+)$/\1/p')
fi
if [ $SDA -eq 1 ] ; then
    echo "sdatemp.value" $(smartctl -a /dev/sda | sed -nr 's/.*Temperature_Celsius.*[[:space:]]([0-9]+)$/\1/p')
fi
if [ $SDB -eq 1 ] ; then
    echo "sdbtemp.value" $(smartctl -a /dev/sdb | sed -nr 's/.*Temperature_Celsius.*[[:space:]]([0-9]+)$/\1/p')
fi
