#!/usr/bin/env python
"""Simple event device listener"""

import time

from evdev import Device

DEVICE = '/dev/input/event1'


def main():
    dev = Device(DEVICE)
    for event in dev.loop():
        if event.type == 'EV_KEY':
            print event


if __name__ == "__main__":
    main()
